apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uni-sso
    tier: backend
    deployedBy: deploy-node-app
  name: uni-sso
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uni-sso
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uni-sso
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: 'jefftian/uni-sso'
          imagePullPolicy: Always
          name: uni-sso
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: env
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uni-sso-secrets
                  key: JWT_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: uni-sso-secrets
                  key: MONGODB_URI
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_HOST
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: KEYCLOAK_HOST
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uni-sso-secrets
                  key: KEYCLOAK_CLIENT_SECRET
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
            - node
            - dist/main.js
