# Use postgres/example user/password credentials
version: "3.1"

services:
  local-mongo:
    image: mongo:3.4
    restart: always
    ports:
      - 27017:27017
  local-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
    - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./data/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
    ports:
      - 5432:5432

#  uni-sso:
#    image: jeff-tian/uni-sso
#    restart: always
#    ports:
#      - 3000:3000
