apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-sso
  template:
    metadata:
      labels:
        app: uni-sso
    spec:
      containers:
        - image: 'jefftian/uni-sso:latest'
          name: uni-sso
          env:
            - name: env
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: uni-sso-configmap
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uni-sso-secrets
                  key: JWT_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: uni-sso-secrets
                  key: MONGODB_URI

---
apiVersion: v1
kind: Service
metadata:
  name: uni-sso
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: 'uni-sso'
      port: 3000
  selector:
    app: uni-sso

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uni-sso-configmap
  namespace: jeff-tian
  labels:
    branch: master
data:
  env: 'okteto'
  NODE_ENV: 'production'
